// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[room].tsx";
import * as $1 from "./routes/api/ws.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/CreateRoom.tsx";
import * as $$1 from "./islands/PlayerName.tsx";
import * as $$2 from "./islands/Room.tsx";

const manifest = {
  routes: {
    "./routes/[room].tsx": $0,
    "./routes/api/ws.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/CreateRoom.tsx": $$0,
    "./islands/PlayerName.tsx": $$1,
    "./islands/Room.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
